I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/act2.rpy", line 328, in script call
    call puzzle_bottles # Головоломка з колбами
  File "game/act3.rpy", line 42, in script call
    call MemoryGame  # Вызов метки мини-игры из другого файла
  File "game/memorygame.rpy", line 83, in script
    while not all(revealed):
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/act2.rpy", line 328, in script call
    call puzzle_bottles # Головоломка з колбами
  File "game/act3.rpy", line 42, in script call
    call MemoryGame  # Вызов метки мини-игры из другого файла
  File "game/memorygame.rpy", line 83, in script
    while not all(revealed):
  File "C:\Users\user\Desktop\renpy-8.3.4-sdk\renpy\execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
Mystery University Library: Degerativity Edition 1.0
Tue May 20 02:17:45 2025
